# Generated by Django 3.1.4 on 2020-12-19 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SysLog',
            fields=[
                ('logid', models.IntegerField(primary_key=True, serialize=False)),
                ('author', models.CharField(blank=True, max_length=32, null=True)),
                ('inserted', models.DateTimeField(blank=True, null=True)),
                ('exceptxt', models.CharField(blank=True, max_length=255, null=True)),
                ('querytxt', models.CharField(blank=True, max_length=255, null=True)),
                ('errtxt', models.CharField(blank=True, max_length=255, null=True)),
                ('msgtxt', models.CharField(blank=True, max_length=255, null=True)),
                ('key1', models.CharField(blank=True, max_length=32, null=True)),
                ('val1', models.CharField(blank=True, max_length=32, null=True)),
                ('key2', models.CharField(blank=True, max_length=32, null=True)),
                ('val2', models.CharField(blank=True, max_length=32, null=True)),
                ('key3', models.CharField(blank=True, max_length=32, null=True)),
                ('val3', models.CharField(blank=True, max_length=32, null=True)),
                ('key4', models.CharField(blank=True, max_length=32, null=True)),
                ('val4', models.CharField(blank=True, max_length=32, null=True)),
                ('key5', models.CharField(blank=True, max_length=32, null=True)),
                ('val5', models.CharField(blank=True, max_length=32, null=True)),
            ],
            options={
                'db_table': 'SysLog',
                'ordering': ['-logid'],
                'get_latest_by': 'logid',
                'managed': True,
            },
        ),
    ]
