# Generated by Django 3.1.4 on 2020-12-19 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClockApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('cID', models.IntegerField(db_column='cID', primary_key=True, serialize=False)),
                ('cDateCreated', models.DateTimeField(db_column='cDateCreated')),
                ('cName', models.CharField(db_column='cName', max_length=64)),
                ('cPhone', models.CharField(db_column='cPhone', max_length=10)),
                ('cGender', models.CharField(db_column='cGender', max_length=1)),
                ('cDOB', models.DateTimeField(blank=True, db_column='cDOB', null=True)),
                ('cEmail', models.CharField(db_column='cEmail', max_length=128)),
                ('cPW', models.CharField(db_column='cPW', max_length=16)),
                ('cAddress1', models.CharField(db_column='cAddress1', max_length=64)),
                ('cAddress2', models.CharField(db_column='cAddress2', max_length=16)),
                ('cCity', models.CharField(db_column='cCity', max_length=16)),
                ('cState', models.CharField(db_column='cState', max_length=2)),
                ('cZip', models.CharField(db_column='cZip', max_length=7)),
            ],
            options={
                'db_table': 'Customer',
                'ordering': ['-cName'],
                'get_latest_by': 'cID',
                'managed': True,
            },
        ),
    ]
