# Generated by Django 3.1.4 on 2020-12-19 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClockApp', '0002_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='cDateCreated',
            field=models.DateTimeField(blank=True, db_column='cDateCreated', null=True),
        ),
    ]
